# Coleta

In [34]:
from pysus import SIA
sia = SIA().load()

In [35]:
sia.metadata

{'long_name': 'Sistema de Informações Ambulatoriais',
 'source': 'http://sia.datasus.gov.br/principal/index.php',
 'description': 'O Sistema de Informação Ambulatorial (SIA) foi instituído pela Portaria GM/MS n.º 896 de 29 de junho de 1990. Originalmente, o SIA foi concebido a partir do projeto SICAPS (Sistema de Informação e Controle Ambulatorial da Previdência Social), em que os conceitos, os objetivos e as diretrizes criados para o desenvolvimento do SICAPS foram extremamente importantes e amplamente utilizados para o desenvolvimento do SIA, tais como: (i) o acompanhamento das programações físicas e orçamentárias; (ii) o acompanhamento das ações de saúde produzidas; (iii) a agilização do pagamento e controle orçamentário e financeiro; e (iv) a formação de banco de dados para contribuir com a construção do SUS.'}

In [36]:
sia.groups

{'AB': 'APAC de Cirurgia Bariátrica',
 'ABO': 'APAC de Acompanhamento Pós Cirurgia Bariátrica',
 'ACF': 'APAC de Confecção de Fístula',
 'AD': 'APAC de Laudos Diversos',
 'AM': 'APAC de Medicamentos',
 'AMP': 'APAC de Acompanhamento Multiprofissional',
 'AN': 'APAC de Nefrologia',
 'AQ': 'APAC de Quimioterapia',
 'AR': 'APAC de Radioterapia',
 'ATD': 'APAC de Tratamento Dialítico',
 'BI': 'Boletim de Produção Ambulatorial individualizado',
 'IMPBO': '',
 'PA': 'Produção Ambulatorial',
 'PAM': '',
 'PAR': '',
 'PAS': '',
 'PS': 'RAAS Psicossocial',
 'SAD': 'RAAS de Atenção Domiciliar'}

In [37]:
print(str(len(sia.get_files(["ATD", "BI"]))) + " files")

9198 files

In [38]:
sia.get_files("ATD", uf="SP", year=2014)

[ATDSP1408.dbc, ATDSP1409.dbc, ATDSP1410.dbc, ATDSP1411.dbc, ATDSP1412.dbc]

In [39]:
# Coleta os arquivos de 2014 a 2024
files = []
for year in range(2014, 2025):
    files += sia.get_files("ATD", uf="RS", year=year)

In [40]:
files

[ATDRS1408.dbc,
 ATDRS1409.dbc,
 ATDRS1410.dbc,
 ATDRS1411.dbc,
 ATDRS1412.dbc,
 ATDRS1501.dbc,
 ATDRS1502.dbc,
 ATDRS1503.dbc,
 ATDRS1504.dbc,
 ATDRS1505.dbc,
 ATDRS1506.dbc,
 ATDRS1507.dbc,
 ATDRS1508.dbc,
 ATDRS1509.dbc,
 ATDRS1510.dbc,
 ATDRS1511.dbc,
 ATDRS1512.dbc,
 ATDRS1601.dbc,
 ATDRS1602.dbc,
 ATDRS1603.dbc,
 ATDRS1604.dbc,
 ATDRS1605.dbc,
 ATDRS1606.dbc,
 ATDRS1607.dbc,
 ATDRS1608.dbc,
 ATDRS1609.dbc,
 ATDRS1610.dbc,
 ATDRS1611.dbc,
 ATDRS1612.dbc,
 ATDRS1701.dbc,
 ATDRS1702.dbc,
 ATDRS1703.dbc,
 ATDRS1704.dbc,
 ATDRS1705.dbc,
 ATDRS1706.dbc,
 ATDRS1707.dbc,
 ATDRS1708.dbc,
 ATDRS1709.dbc,
 ATDRS1710.dbc,
 ATDRS1711.dbc,
 ATDRS1712.dbc,
 ATDRS1801.dbc,
 ATDRS1802.dbc,
 ATDRS1803.dbc,
 ATDRS1804.dbc,
 ATDRS1805.dbc,
 ATDRS1806.dbc,
 ATDRS1807.dbc,
 ATDRS1808.dbc,
 ATDRS1809.dbc,
 ATDRS1810.dbc,
 ATDRS1811.dbc,
 ATDRS1812.dbc,
 ATDRS1901.dbc,
 ATDRS1902.dbc,
 ATDRS1903.dbc,
 ATDRS1904.dbc,
 ATDRS1905.dbc,
 ATDRS1906.dbc,
 ATDRS1907.dbc,
 ATDRS1908.dbc,
 ATDRS1909.dbc,
 ATDRS1910.dbc,
 ATDRS1911.dbc,
 ATDRS1912.dbc,
 ATDRS2001.dbc,
 ATDRS2002.dbc,
 ATDRS2003.dbc,
 ATDRS2004.dbc,
 ATDRS2005.dbc,
 ATDRS2006.dbc,
 ATDRS2007.dbc,
 ATDRS2008.dbc,
 ATDRS2009.dbc,
 ATDRS2010.dbc,
 ATDRS2011.dbc,
 ATDRS2012.dbc,
 ATDRS2101.dbc,
 ATDRS2102.dbc,
 ATDRS2103.dbc,
 ATDRS2104.dbc,
 ATDRS2105.dbc,
 ATDRS2106.dbc,
 ATDRS2107.dbc,
 ATDRS2108.dbc,
 ATDRS2109.dbc,
 ATDRS2110.dbc,
 ATDRS2111.dbc,
 ATDRS2112.dbc,
 ATDRS2201.dbc,
 ATDRS2202.dbc,
 ATDRS2203.dbc,
 ATDRS2204.dbc,
 ATDRS2205.dbc,
 ATDRS2206.dbc,
 ATDRS2207.dbc,
 ATDRS2208.dbc,
 ATDRS2209.dbc,
 ATDRS2210.dbc,
 ATDRS2211.dbc,
 ATDRS2212.dbc,
 ATDRS2301.dbc,
 ATDRS2302.dbc,
 ATDRS2303.dbc,
 ATDRS2304.dbc,
 ATDRS2305.dbc,
 ATDRS2306.dbc,
 ATDRS2307.dbc,
 ATDRS2308.dbc,
 ATDRS2309.dbc,
 ATDRS2310.dbc,
 ATDRS2311.dbc,
 ATDRS2312.dbc,
 ATDRS2401.dbc,
 ATDRS2402.dbc,
 ATDRS2403.dbc,
 ATDRS2404.dbc,
 ATDRS2405.dbc,
 ATDRS2406.dbc,
 ATDRS2407.dbc,
 ATDRS2408.dbc,
 ATDRS2409.dbc,
 ATDRS2410.dbc,
 ATDRS2411.dbc,
 ATDRS2412.dbc]

In [41]:
#sia.download(files)
import os
import pandas as pd
os.makedirs("dados-raw", exist_ok=True)
sia.download(files, local_dir="dados-raw")

ATDRS2412.parquet: 100%|██████████████████▉| 10.2k/10.2k [00:00<00:00, 21.0kB/s]

[dados-raw/ATDRS1408.parquet,
 dados-raw/ATDRS1409.parquet,
 dados-raw/ATDRS1410.parquet,
 dados-raw/ATDRS1411.parquet,
 dados-raw/ATDRS1412.parquet,
 dados-raw/ATDRS1501.parquet,
 dados-raw/ATDRS1502.parquet,
 dados-raw/ATDRS1503.parquet,
 dados-raw/ATDRS1504.parquet,
 dados-raw/ATDRS1505.parquet,
 dados-raw/ATDRS1506.parquet,
 dados-raw/ATDRS1507.parquet,
 dados-raw/ATDRS1508.parquet,
 dados-raw/ATDRS1509.parquet,
 dados-raw/ATDRS1510.parquet,
 dados-raw/ATDRS1511.parquet,
 dados-raw/ATDRS1512.parquet,
 dados-raw/ATDRS1601.parquet,
 dados-raw/ATDRS1602.parquet,
 dados-raw/ATDRS1603.parquet,
 dados-raw/ATDRS1604.parquet,
 dados-raw/ATDRS1605.parquet,
 dados-raw/ATDRS1606.parquet,
 dados-raw/ATDRS1607.parquet,
 dados-raw/ATDRS1608.parquet,
 dados-raw/ATDRS1609.parquet,
 dados-raw/ATDRS1610.parquet,
 dados-raw/ATDRS1611.parquet,
 dados-raw/ATDRS1612.parquet,
 dados-raw/ATDRS1701.parquet,
 dados-raw/ATDRS1702.parquet,
 dados-raw/ATDRS1703.parquet,
 dados-raw/ATDRS1704.parquet,
 dados-raw/ATDRS1705.parquet,
 dados-raw/ATDRS1706.parquet,
 dados-raw/ATDRS1707.parquet,
 dados-raw/ATDRS1708.parquet,
 dados-raw/ATDRS1709.parquet,
 dados-raw/ATDRS1710.parquet,
 dados-raw/ATDRS1711.parquet,
 dados-raw/ATDRS1712.parquet,
 dados-raw/ATDRS1801.parquet,
 dados-raw/ATDRS1802.parquet,
 dados-raw/ATDRS1803.parquet,
 dados-raw/ATDRS1804.parquet,
 dados-raw/ATDRS1805.parquet,
 dados-raw/ATDRS1806.parquet,
 dados-raw/ATDRS1807.parquet,
 dados-raw/ATDRS1808.parquet,
 dados-raw/ATDRS1809.parquet,
 dados-raw/ATDRS1810.parquet,
 dados-raw/ATDRS1811.parquet,
 dados-raw/ATDRS1812.parquet,
 dados-raw/ATDRS1901.parquet,
 dados-raw/ATDRS1902.parquet,
 dados-raw/ATDRS1903.parquet,
 dados-raw/ATDRS1904.parquet,
 dados-raw/ATDRS1905.parquet,
 dados-raw/ATDRS1906.parquet,
 dados-raw/ATDRS1907.parquet,
 dados-raw/ATDRS1908.parquet,
 dados-raw/ATDRS1909.parquet,
 dados-raw/ATDRS1910.parquet,
 dados-raw/ATDRS1911.parquet,
 dados-raw/ATDRS1912.parquet,
 dados-raw/ATDRS2001.parquet,
 dados-raw/ATDRS2002.parquet,
 dados-raw/ATDRS2003.parquet,
 dados-raw/ATDRS2004.parquet,
 dados-raw/ATDRS2005.parquet,
 dados-raw/ATDRS2006.parquet,
 dados-raw/ATDRS2007.parquet,
 dados-raw/ATDRS2008.parquet,
 dados-raw/ATDRS2009.parquet,
 dados-raw/ATDRS2010.parquet,
 dados-raw/ATDRS2011.parquet,
 dados-raw/ATDRS2012.parquet,
 dados-raw/ATDRS2101.parquet,
 dados-raw/ATDRS2102.parquet,
 dados-raw/ATDRS2103.parquet,
 dados-raw/ATDRS2104.parquet,
 dados-raw/ATDRS2105.parquet,
 dados-raw/ATDRS2106.parquet,
 dados-raw/ATDRS2107.parquet,
 dados-raw/ATDRS2108.parquet,
 dados-raw/ATDRS2109.parquet,
 dados-raw/ATDRS2110.parquet,
 dados-raw/ATDRS2111.parquet,
 dados-raw/ATDRS2112.parquet,
 dados-raw/ATDRS2201.parquet,
 dados-raw/ATDRS2202.parquet,
 dados-raw/ATDRS2203.parquet,
 dados-raw/ATDRS2204.parquet,
 dados-raw/ATDRS2205.parquet,
 dados-raw/ATDRS2206.parquet,
 dados-raw/ATDRS2207.parquet,
 dados-raw/ATDRS2208.parquet,
 dados-raw/ATDRS2209.parquet,
 dados-raw/ATDRS2210.parquet,
 dados-raw/ATDRS2211.parquet,
 dados-raw/ATDRS2212.parquet,
 dados-raw/ATDRS2301.parquet,
 dados-raw/ATDRS2302.parquet,
 dados-raw/ATDRS2303.parquet,
 dados-raw/ATDRS2304.parquet,
 dados-raw/ATDRS2305.parquet,
 dados-raw/ATDRS2306.parquet,
 dados-raw/ATDRS2307.parquet,
 dados-raw/ATDRS2308.parquet,
 dados-raw/ATDRS2309.parquet,
 dados-raw/ATDRS2310.parquet,
 dados-raw/ATDRS2311.parquet,
 dados-raw/ATDRS2312.parquet,
 dados-raw/ATDRS2401.parquet,
 dados-raw/ATDRS2402.parquet,
 dados-raw/ATDRS2403.parquet,
 dados-raw/ATDRS2404.parquet,
 dados-raw/ATDRS2405.parquet,
 dados-raw/ATDRS2406.parquet,
 dados-raw/ATDRS2407.parquet,
 dados-raw/ATDRS2408.parquet,
 dados-raw/ATDRS2409.parquet,
 dados-raw/ATDRS2410.parquet,
 dados-raw/ATDRS2411.parquet,
 dados-raw/ATDRS2412.parquet]

In [44]:
import pandas as pd
import os

# Caminho da pasta do mês (ex: setembro de 2021)
caminho_pasta = "dados-raw/ATDRS2210.parquet"

arquivos = [os.path.join(caminho_pasta, f) for f in os.listdir(caminho_pasta) if f.endswith(".parquet")]
df = pd.concat([pd.read_parquet(arq) for arq in arquivos], ignore_index=True)
print("Colunas disponíveis:")
print(df.columns.tolist())

print("\nPrimeiras linhas:")
print(df.head())

Colunas disponíveis:
['AP_MVM', 'AP_CONDIC', 'AP_GESTAO', 'AP_CODUNI', 'AP_AUTORIZ', 'AP_CMP', 'AP_PRIPAL', 'AP_VL_AP', 'AP_UFMUN', 'AP_TPUPS', 'AP_TIPPRE', 'AP_MN_IND', 'AP_CNPJCPF', 'AP_CNPJMNT', 'AP_CNSPCN', 'AP_COIDADE', 'AP_NUIDADE', 'AP_SEXO', 'AP_RACACOR', 'AP_MUNPCN', 'AP_UFNACIO', 'AP_CEPPCN', 'AP_UFDIF', 'AP_MNDIF', 'AP_DTINIC', 'AP_DTFIM', 'AP_TPATEN', 'AP_TPAPAC', 'AP_MOTSAI', 'AP_OBITO', 'AP_ENCERR', 'AP_PERMAN', 'AP_ALTA', 'AP_TRANSF', 'AP_DTOCOR', 'AP_CODEMI', 'AP_CATEND', 'AP_APACANT', 'AP_UNISOL', 'AP_DTSOLIC', 'AP_DTAUT', 'AP_CIDCAS', 'AP_CIDPRI', 'AP_CIDSEC', 'AP_ETNIA', 'ATD_CARACT', 'ATD_DTPDR', 'ATD_DTCLI', 'ATD_ACEVAS', 'ATD_MAISNE', 'ATD_SITINI', 'ATD_SITTRA', 'ATD_SEAPTO', 'ATD_HB', 'ATD_FOSFOR', 'ATD_KTVSEM', 'ATD_TRU', 'ATD_ALBUMI', 'ATD_PTH', 'ATD_HIV', 'ATD_HCV', 'ATD_HBSAG', 'ATD_INTERC', 'ATD_SEPERI', 'AP_NATJUR']

Primeiras linhas:
   AP_MVM AP_CONDIC AP_GESTAO AP_CODUNI     AP_AUTORIZ  AP_CMP   AP_PRIPAL  \
0  202210        EP    430000   2244357  4322200814349  202210  0305010115
1  202210        EP    430000   2233312  4322209708212  202210  0305010115
2  202210        EP    430000   2228602  4322213677090  202210  0305010115
3  202210        EP    430000   2231778  4322210831356  202210  0305010115
4  202210        EP    430000   2233304  4322209692548  202210  0305010115

               AP_VL_AP AP_UFMUN AP_TPUPS  ... ATD_KTVSEM ATD_TRU ATD_ALBUMI  \
0               3494.87   431740       05  ...       1.30    66.7       3.9
1               2403.01   431880       05  ...       1.45    71.2       3.9
2               3466.50   430850       05  ...       1.81    79.0       4.1
3               3355.70   432300       39  ...       0.75    46.2       4.3
4               3467.55   431560       36  ...       1.15    61.2       4.0

  ATD_PTH ATD_HIV ATD_HCV ATD_HBSAG ATD_INTERC ATD_SEPERI AP_NATJUR
0    25         N       P         N          N          N      3999
1    446        P       N         N          N          N      3999
2    153        N       P         N          N          N      3999
3    581        N       P         N          N          N      2062
4    60         P       P         N          N          N      2062

[5 rows x 65 columns]

In [47]:
df['AP_UFMUN'].value_counts()

AP_UFMUN
431490    1235
431690     341
431440     331
431410     321
430510     226
431350     170
431560     164
430920     163
431020     156
431750     155
431140     140
430060     137
430310     132
431680     129
430930     122
430390     122
431340     116
432150     114
431870     112
430300     111
431240     111
432120     109
430850     102
431720      95
430460      95
430610      93
432250      93
430160      90
432300      85
430700      80
432260      79
430470      76
430350      69
431710      56
432000      56
432240      55
430040      54
431800      53
432080      50
431640      50
431330      47
431830      45
430210      41
431740      40
430770      35
431880      29
431060      22
Name: count, dtype: int64

In [21]:
df['PA_IDADE'].value_counts()

PA_IDADE
999    206293
063     55628
061     54740
059     54218
060     54209
        ...
111         3
120         2
108         2
117         1
129         1
Name: count, Length: 118, dtype: int64

In [22]:
df['IDADEMIN'].value_counts()

IDADEMIN
0      2957505
25       31565
19       29307
10       21941
35       21905
9        14851
2        14427
         12778
12       10787
8         9247
18        8410
5         7721
16        6551
3         4078
4         4020
13        3334
1         2371
40        2262
15        2019
7         1683
6          808
60         518
14         217
50         125
65         121
20          90
45          78
Name: count, dtype: int64

In [23]:
df['IDADEMAX'].value_counts()

IDADEMAX
130    3083143
64       31517
60       19114
         12778
69        6003
80        3641
19        3447
49        2587
5         1629
18        1390
9         1318
55         825
0          337
90         323
22         321
75          87
110         68
4           55
10          23
12          23
35          21
17          17
3           15
50          13
2           10
70           5
30           3
1            3
40           2
20           1
Name: count, dtype: int64

In [24]:
df['PA_FLIDADE'].value_counts()

PA_FLIDADE
1    2952768
3     203173
0      12778
Name: count, dtype: int64

In [49]:
print(df.dtypes)

AP_MVM        object
AP_CONDIC     object
AP_GESTAO     object
AP_CODUNI     object
AP_AUTORIZ    object
               ...
ATD_HCV       object
ATD_HBSAG     object
ATD_INTERC    object
ATD_SEPERI    object
AP_NATJUR     object
Length: 65, dtype: object

# Limpeza

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5842 entries, 0 to 5841
Data columns (total 64 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   AP_MVM      5842 non-null   object
 1   AP_CONDIC   5842 non-null   object
 2   AP_GESTAO   5842 non-null   object
 3   AP_CODUNI   5842 non-null   object
 4   AP_AUTORIZ  5842 non-null   object
 5   AP_CMP      5842 non-null   object
 6   AP_PRIPAL   5842 non-null   object
 7   AP_VL_AP    5842 non-null   object
 8   AP_UFMUN    5842 non-null   object
 9   AP_TPUPS    5842 non-null   object
 10  AP_TIPPRE   5842 non-null   object
 11  AP_MN_IND   5842 non-null   object
 12  AP_CNPJCPF  5842 non-null   object
 13  AP_CNPJMNT  5842 non-null   object
 14  AP_CNSPCN   5842 non-null   object
 15  AP_COIDADE  5842 non-null   object
 16  AP_NUIDADE  5842 non-null   object
 17  AP_SEXO     5842 non-null   object
 18  AP_RACACOR  5842 non-null   object
 19  AP_MUNPCN   5842 non-null   object
 20  AP_UFNACIO  5842 non-null   object
 21  AP_CEPPCN   5842 non-null   object
 22  AP_UFDIF    5842 non-null   object
 23  AP_MNDIF    5842 non-null   object
 24  AP_DTINIC   5842 non-null   object
 25  AP_DTFIM    5842 non-null   object
 26  AP_TPATEN   5842 non-null   object
 27  AP_TPAPAC   5842 non-null   object
 28  AP_MOTSAI   5842 non-null   object
 29  AP_OBITO    5842 non-null   object
 30  AP_ENCERR   5842 non-null   object
 31  AP_PERMAN   5842 non-null   object
 32  AP_ALTA     5842 non-null   object
 33  AP_TRANSF   5842 non-null   object
 34  AP_DTOCOR   5842 non-null   object
 35  AP_CODEMI   5842 non-null   object
 36  AP_CATEND   5842 non-null   object
 37  AP_APACANT  5842 non-null   object
 38  AP_UNISOL   5842 non-null   object
 39  AP_DTSOLIC  5842 non-null   object
 40  AP_DTAUT    5842 non-null   object
 41  AP_CIDCAS   5842 non-null   object
 42  AP_CIDPRI   5842 non-null   object
 43  AP_CIDSEC   5842 non-null   object
 44  AP_ETNIA    5842 non-null   object
 45  ATD_CARACT  5842 non-null   object
 46  ATD_DTPDR   5842 non-null   object
 47  ATD_DTCLI   5842 non-null   object
 48  ATD_ACEVAS  5842 non-null   object
 49  ATD_MAISNE  5842 non-null   object
 50  ATD_SITINI  5842 non-null   object
 51  ATD_SITTRA  5842 non-null   object
 52  ATD_SEAPTO  5842 non-null   object
 53  ATD_HB      5842 non-null   object
 54  ATD_FOSFOR  5842 non-null   object
 55  ATD_KTVSEM  5842 non-null   object
 56  ATD_TRU     5842 non-null   object
 57  ATD_ALBUMI  5842 non-null   object
 58  ATD_PTH     5842 non-null   object
 59  ATD_HIV     5842 non-null   object
 60  ATD_HCV     5842 non-null   object
 61  ATD_HBSAG   5842 non-null   object
 62  ATD_INTERC  5842 non-null   object
 63  ATD_SEPERI  5842 non-null   object
dtypes: object(64)
memory usage: 2.9+ MB

In [64]:
caminho_pasta = "dados-raw"

arquivos_dialise = [
    os.path.join(caminho_pasta, f)
    for f in os.listdir(caminho_pasta)
    if f.endswith(".parquet")
]
df = pd.concat([pd.read_parquet(f) for f in arquivos_dialise], ignore_index=True)

In [143]:
df['AP_PRIPAL'].value_counts()

AP_PRIPAL
0305010107    650159
0305010115     65494
0305010166     44607
0305010182      1869
0305010204       314
0305010026       242
                   3
Name: count, dtype: int64

In [64]:
# Filtro 1: Procedimentos de diálise
#df = df[df['AP_PRIPAL'].isin(procedimentos_validos)]

In [144]:
df['AP_UFMUN'].value_counts()

AP_UFMUN
431490    156398
431440     42199
431690     36859
431410     36130
430510     26961
431750     20766
431350     20363
431560     19260
430920     19173
431020     17181
430060     16607
430310     16133
431340     15814
430460     15813
432120     15055
430300     15003
431680     14471
430390     13969
431870     13570
431140     13193
431240     12495
430160     12290
432150     11533
431720     11515
430610     11481
432250     11203
430850     11107
432300     10804
430930     10326
430700      9600
430770      9296
430350      9129
432260      8618
430470      7824
430040      7221
431710      6942
431800      6566
432240      6074
430210      5900
431830      5633
431640      5527
432080      5331
431330      5114
431740      4476
431880      3643
432000      3051
431060      2844
430780      2007
430440       220
Name: count, dtype: int64

In [145]:
#df = df[df['AP_UFMUN'] == '431490']
#df.info()

In [146]:
df['AP_NUIDADE'].value_counts(ascending=True)

AP_NUIDADE
00       23
98       30
99       30
97       62
04       69
      ...
60    20649
63    20651
62    20685
64    21045
61    21172
Name: count, Length: 100, dtype: int64

In [65]:
df.groupby(['AP_NUIDADE', 'AP_COIDADE']).size()

AP_NUIDADE  AP_COIDADE
00          2               3
            5              20
01          3              16
            4             225
            5              11
                         ...
95          4              83
96          4             100
97          4              62
98          4              30
99          4              30
Length: 117, dtype: int64

In [75]:
df.head()

,AP_MVM,AP_CONDIC,AP_GESTAO,AP_CODUNI,AP_AUTORIZ,AP_CMP,AP_PRIPAL,AP_VL_AP,AP_UFMUN,AP_TPUPS,...,ATD_FOSFOR,ATD_KTVSEM,ATD_TRU,ATD_ALBUMI,ATD_PTH,ATD_HIV,ATD_HCV,ATD_HBSAG,ATD_INTERC,ATD_SEPERI
0,201408,MN,431490,2237253,4314203219370,201408,0305010166,2149.62,431490,05,...,0,0,0,4,0,N,N,N,I,I
1,201408,MN,431490,2262568,4314203319756,201408,0305010166,400.00,431490,05,...,99,99,0,0,0,N,N,N,S,I
2,201408,MN,431490,2262568,4314203240490,201408,0305010166,2149.62,431490,05,...,99,99,0,0,0,N,N,N,N,N
3,201408,MN,431490,2237601,4314201305645,201408,0305010166,2204.49,431490,05,...,07.5,0000,0011,0004,0368,N,N,N,I,I
4,201408,MN,431490,2237598,4314203319162,201408,0305010166,1529.46,431490,05,...,6,2,1,4,534,N,P,N,S,N

In [42]:
df['AP_NUIDADE'].value_counts()

AP_NUIDADE
61    21172
64    21045
62    20685
63    20651
60    20649
      ...
4        69
97       62
99       30
98       30
0        23
Name: count, Length: 100, dtype: int64

In [41]:
df['AP_COIDADE'].value_counts()

AP_COIDADE
4    762457
3       180
5        43
2         8
Name: count, dtype: int64

In [66]:
df['AP_COIDADE'] = pd.to_numeric(df['AP_COIDADE'], errors='coerce')
df['AP_NUIDADE'] = pd.to_numeric(df['AP_NUIDADE'], errors='coerce')

def calcular_idade(row):
    if pd.isna(row['AP_COIDADE']) or pd.isna(row['AP_NUIDADE']):
        return None
    coidade = row['AP_COIDADE']
    nuidade = row['AP_NUIDADE']
    if coidade == 1:  # Anos
        return nuidade
    elif coidade == 2:  # Meses
        return nuidade / 12
    elif coidade == 3:  # Dias
        return nuidade / 365
    elif coidade == 4:  # Anos (padrão para a maioria dos casos)
        return nuidade
    else:  # Outros códigos (ex.: 5 ou inválidos)
        return None

df['idade'] = df.apply(calcular_idade, axis=1)
df = df[df['idade'] < 18].copy()  
def calcular_faixa_etaria(idade):
    if pd.isna(idade) or idade < 0:
        return "Desconhecido"
    elif 0 <= idade <= 5:
        return "0-5 anos"
    elif 6 <= idade <= 12:
        return "6-12 anos"
    elif 13 <= idade <= 17:
        return "13-17 anos"
    return "Fora do Escopo"

df['faixa_etaria'] = df['idade'].apply(calcular_faixa_etaria)
df['ANO'] = df['AP_CMP'].astype(str).str[:4]

In [67]:
df['faixa_etaria'].value_counts()

faixa_etaria
13-17 anos    2033
6-12 anos      910
0-5 anos       790
Name: count, dtype: int64

In [68]:
df['idade'].value_counts()

idade
17.000000    638
16.000000    486
15.000000    383
14.000000    322
1.000000     225
13.000000    204
12.000000    179
11.000000    160
10.000000    153
2.000000     133
7.000000     124
3.000000     115
9.000000     110
6.000000      93
8.000000      91
5.000000      71
4.000000      58
0.027397      21
0.016438      21
0.021918      20
0.030137      19
0.024658      19
0.013699      17
0.002740      16
0.005479      14
0.008219      13
0.010959      11
0.019178       9
0.000000       3
0.166667       3
2.250000       1
1.250000       1
Name: count, dtype: int64

In [149]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 542 entries, 778 to 759547
Data columns (total 66 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   AP_MVM      542 non-null    object
 1   AP_CONDIC   542 non-null    object
 2   AP_GESTAO   542 non-null    object
 3   AP_CODUNI   542 non-null    object
 4   AP_AUTORIZ  542 non-null    object
 5   AP_CMP      542 non-null    object
 6   AP_PRIPAL   542 non-null    object
 7   AP_VL_AP    542 non-null    object
 8   AP_UFMUN    542 non-null    object
 9   AP_TPUPS    542 non-null    object
 10  AP_TIPPRE   542 non-null    object
 11  AP_MN_IND   542 non-null    object
 12  AP_CNPJCPF  542 non-null    object
 13  AP_CNPJMNT  542 non-null    object
 14  AP_CNSPCN   542 non-null    object
 15  AP_COIDADE  542 non-null    int64
 16  AP_NUIDADE  542 non-null    int64
 17  AP_SEXO     542 non-null    object
 18  AP_RACACOR  542 non-null    object
 19  AP_MUNPCN   542 non-null    object
 20  AP_UFNACIO  542 non-null    object
 21  AP_CEPPCN   542 non-null    object
 22  AP_UFDIF    542 non-null    object
 23  AP_MNDIF    542 non-null    object
 24  AP_DTINIC   542 non-null    object
 25  AP_DTFIM    542 non-null    object
 26  AP_TPATEN   542 non-null    object
 27  AP_TPAPAC   542 non-null    object
 28  AP_MOTSAI   542 non-null    object
 29  AP_OBITO    542 non-null    object
 30  AP_ENCERR   542 non-null    object
 31  AP_PERMAN   542 non-null    object
 32  AP_ALTA     542 non-null    object
 33  AP_TRANSF   542 non-null    object
 34  AP_DTOCOR   542 non-null    object
 35  AP_CODEMI   542 non-null    object
 36  AP_CATEND   542 non-null    object
 37  AP_APACANT  542 non-null    object
 38  AP_UNISOL   542 non-null    object
 39  AP_DTSOLIC  542 non-null    object
 40  AP_DTAUT    542 non-null    object
 41  AP_CIDCAS   542 non-null    object
 42  AP_CIDPRI   542 non-null    object
 43  AP_CIDSEC   542 non-null    object
 44  AP_ETNIA    542 non-null    object
 45  ATD_CARACT  542 non-null    object
 46  ATD_DTPDR   542 non-null    object
 47  ATD_DTCLI   542 non-null    object
 48  ATD_ACEVAS  542 non-null    object
 49  ATD_MAISNE  542 non-null    object
 50  ATD_SITINI  542 non-null    object
 51  ATD_SITTRA  542 non-null    object
 52  ATD_SEAPTO  542 non-null    object
 53  ATD_HB      542 non-null    object
 54  ATD_FOSFOR  542 non-null    object
 55  ATD_KTVSEM  542 non-null    object
 56  ATD_TRU     542 non-null    object
 57  ATD_ALBUMI  542 non-null    object
 58  ATD_PTH     542 non-null    object
 59  ATD_HIV     542 non-null    object
 60  ATD_HCV     542 non-null    object
 61  ATD_HBSAG   542 non-null    object
 62  ATD_INTERC  542 non-null    object
 63  ATD_SEPERI  542 non-null    object
 64  AP_NATJUR   473 non-null    object
 65  ANO         542 non-null    object
dtypes: int64(2), object(64)
memory usage: 283.7+ KB

In [46]:
df['AP_UFMUN'].value_counts()

AP_UFMUN
431490    2258
431410     199
431440     135
431690      91
432260      90
430510      88
431680      78
431020      73
432120      61
431870      55
431750      54
430040      52
430160      48
430700      42
431710      36
431560      35
430310      31
430610      30
431140      30
430300      28
432240      23
432150      22
431720      22
431240      22
430850      20
430390      20
431340      19
430210      19
431830      11
431800       9
431640       8
430780       6
430770       6
430350       5
430060       4
432250       3
Name: count, dtype: int64

In [69]:
codigos_municipios = {
    431490: "Porto Alegre",
    431410: "Novo Hamburgo",
    431440: "Passo Fundo",
    430610: "Caxias do Sul",
    430040: "Alegrete",
    430510: "Canoas",
    431690: "Santa Rosa",
    430210: "Bagé"
}
df['municipio'] = df['AP_UFMUN'].astype(str).map(codigos_municipios)

In [72]:
df['municipio'].value_counts()

municipio
Porto Alegre     2258
Novo Hamburgo     199
Passo Fundo       135
Santa Rosa         91
Canoas             88
Alegrete           52
Caxias do Sul      30
Bagé               19
Name: count, dtype: int64

In [71]:
codigos_municipios = {
    "431490": "Porto Alegre",
    "431410": "Novo Hamburgo",
    "431440": "Passo Fundo",
    "430610": "Caxias do Sul",
    "430040": "Alegrete",
    "430510": "Canoas",
    "431690": "Santa Rosa",
    "430210": "Bagé"
}
df['municipio'] = df['AP_UFMUN'].astype(str).map(codigos_municipios)

In [50]:
df

,AP_MVM,AP_CONDIC,AP_GESTAO,AP_CODUNI,AP_AUTORIZ,AP_CMP,AP_PRIPAL,AP_VL_AP,AP_UFMUN,AP_TPUPS,...,ATD_HIV,ATD_HCV,ATD_HBSAG,ATD_INTERC,ATD_SEPERI,AP_NATJUR,idade,faixa_etaria,ANO,municipio
48,201408,MN,431490,2237253,4314203318910,201408,0305010182,664.52,431490,05,...,N,N,N,I,I,NaN,16.0,13-17 anos,2014,Porto Alegre
488,201408,EP,430000,2246988,4314204470279,201408,0305010107,2780.74,431410,05,...,N,N,N,N,N,NaN,17.0,13-17 anos,2014,Novo Hamburgo
572,201408,EP,430000,3564150,4314206856520,201408,0305010107,1897.87,430850,39,...,,,,N,I,NaN,16.0,13-17 anos,2014,NaN
731,201408,MN,431490,2237164,4314203295424,201408,0305010204,707.76,431490,36,...,N,N,N,I,I,NaN,9.0,6-12 anos,2014,Porto Alegre
742,201408,MN,431490,2237253,4314201339415,201408,0305010166,2700.87,431490,05,...,N,N,N,I,I,NaN,10.0,6-12 anos,2014,Porto Alegre
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
760548,202404,PG,431490,2237253,4324203445672,202404,0305010166,3342.62,431490,05,...,N,N,N,I,I,3069,13.0,13-17 anos,2024,Porto Alegre
760965,202404,EP,430000,2246929,4324200824560,202404,0305010107,3132.61,431410,05,...,N,N,N,S,S,3999,14.0,13-17 anos,2024,Novo Hamburgo
761342,202404,PG,431710,2248220,4324205325100,202404,0305010107,3172.24,431710,05,...,N,N,N,N,N,3999,17.0,13-17 anos,2024,NaN
761350,202404,PG,431490,2237253,4324203512410,202404,0305010107,3614.55,431490,05,...,N,N,N,I,I,3069,16.0,13-17 anos,2024,Porto Alegre
762241,202404,PG,431490,2237253,4324203444770,202404,0305010166,3342.62,431490,05,...,N,N,N,I,I,3069,7.0,6-12 anos,2024,Porto Alegre

In [74]:
proc_map = {
    '0305010026': 'Hemodiálise (aguda)',
    '0305010107': 'Diálise peritoneal ambulatorial contínua (CAPD)',
    '0305010115': 'Diálise peritoneal automatizada (APD)',
    '0305010166': 'Hemodiálise crônica',
    '0305010182': 'Hemodiálise diária',
    '0305010204': 'Hemodiálise pediátrica'
}

gestao_map = {
    '430000': 'Estado do RS',
    '430210': 'Bagé',
    '430510': 'Canoas',
    '430610': 'Caxias do Sul',
    '431410': 'Novo Hamburgo',
    '431440': 'Passo Fundo',
    '431490': 'Porto Alegre'
}

condic_map = {
    'MN': 'Municipalizado',
    'EP': 'Estadualizado / Estadual',
    'PG': 'Gestão Plena'
}

tpups_map = {
    '05': 'Hospital Geral',
    '36': 'Centro de Terapia Renal Substitutiva',
    '39': 'Hospital Especializado'
}

tippre_map = {
    '00': 'Ambulatorial Individualizado',
    '30': 'Alta Complexidade',
    '61': 'TRS - Diálise'
}

sexo_map = {
    'M': 'Masculino',
    'F': 'Feminino'
}

raca_map = {
    '01': 'Branca',
    '02': 'Preta',
    '03': 'Parda',
    '99': 'Ignorado'
}

codigos_municipios = {
    431490: "Porto Alegre",
    431410: "Novo Hamburgo",
    431440: "Passo Fundo",
    430610: "Caxias do Sul",
    430040: "Alegrete",
    430510: "Canoas",
    431690: "Santa Rosa",
    430210: "Bagé"
}

unidade_map = {
    '2223538': 'Hospital Universitário – Canoas',
    '2237253': 'Hospital de Clínicas de Porto Alegre (HCPA)',
    '2237601': 'Santa Casa de Misericórdia de Porto Alegre',
    '2241021': 'Hospital São Vicente de Paulo – Passo Fundo',
    '2244306': 'Hospital de Caridade de Ijuí',
    '2246988': 'Hospital Regina – Novo Hamburgo',
    '2247984': 'Hospital Geral de Caxias do Sul',
    '2253046': 'Hospital Vida e Saúde – Santa Rosa',
    '2262509': 'Hospital de Caridade de Alegrete',
    '2262568': 'Santa Casa de Caridade de Bagé',
    '2263858': 'Hospital Municipal – Bagé'
}

df['AP_PRIPAL_str'] = df['AP_PRIPAL'].astype(str)
df['AP_CODUNI_str'] = df['AP_CODUNI'].astype(str)
df['AP_GESTAO_str'] = df['AP_GESTAO'].astype(str)
df['AP_CONDIC_str'] = df['AP_CONDIC'].astype(str)
df['AP_TPUPS_str'] = df['AP_TPUPS'].astype(str)
df['AP_TIPPRE_str'] = df['AP_TIPPRE'].astype(str)
df['AP_RACACOR_str'] = df['AP_RACACOR'].astype(str)

df['procedimento_nome'] = df['AP_PRIPAL_str'].map(proc_map).fillna('Desconhecido')
df['unidade_nome'] = df['AP_CODUNI_str'].map(unidade_map).fillna('Desconhecido')
df['gestao_desc'] = df['AP_GESTAO_str'].map(gestao_map).fillna('Outro')
df['condicao_desc'] = df['AP_CONDIC_str'].map(condic_map).fillna('Outro')
df['tpups_desc'] = df['AP_TPUPS_str'].map(tpups_map).fillna('Outro')
df['tippre_desc'] = df['AP_TIPPRE_str'].map(tippre_map).fillna('Outro')
df['sexo_desc'] = df['AP_SEXO'].map(sexo_map).fillna('Ignorado')
df['raca_desc'] = df['AP_RACACOR_str'].map(raca_map).fillna('Ignorado')
df['AP_UFMUN_int'] = df['AP_UFMUN'].astype(int)
df['municipio'] = df['AP_UFMUN_int'].map(codigos_municipios).fillna('Outro')
if 'AP_MUNPCN' in df.columns:
    df['AP_MUNPCN_int'] = df['AP_MUNPCN'].astype(int)
    df['municipio_origem'] = df['AP_MUNPCN_int'].map(codigos_municipios).fillna('Outro')

df['ANO'] = df['AP_CMP'].astype(str).str[:4]


print("\n✅ Exemplo de dados enriquecidos:")
print(df[[
    'AP_PRIPAL', 'procedimento_nome',
    'AP_CODUNI', 'unidade_nome',
    'AP_GESTAO', 'gestao_desc',
    'AP_CONDIC', 'condicao_desc',
    'AP_TPUPS', 'tpups_desc',
    'AP_TIPPRE', 'tippre_desc',
    'AP_SEXO', 'sexo_desc',
    'AP_RACACOR', 'raca_desc',
    'AP_UFMUN', 'municipio',
    'ANO'
]].head())

✅ Exemplo de dados enriquecidos:
      AP_PRIPAL                                procedimento_nome AP_CODUNI  \
48   0305010182                               Hemodiálise diária   2237253
488  0305010107  Diálise peritoneal ambulatorial contínua (CAPD)   2246988
572  0305010107  Diálise peritoneal ambulatorial contínua (CAPD)   3564150
731  0305010204                           Hemodiálise pediátrica   2237164
742  0305010166                              Hemodiálise crônica   2237253

                                    unidade_nome AP_GESTAO   gestao_desc  \
48   Hospital de Clínicas de Porto Alegre (HCPA)    431490  Porto Alegre
488              Hospital Regina – Novo Hamburgo    430000  Estado do RS
572                                 Desconhecido    430000  Estado do RS
731                                 Desconhecido    431490  Porto Alegre
742  Hospital de Clínicas de Porto Alegre (HCPA)    431490  Porto Alegre

    AP_CONDIC             condicao_desc AP_TPUPS  \
48         MN            Municipalizado       05
488        EP  Estadualizado / Estadual       05
572        EP  Estadualizado / Estadual       39
731        MN            Municipalizado       36
742        MN            Municipalizado       05

                               tpups_desc AP_TIPPRE    tippre_desc AP_SEXO  \
48                         Hospital Geral        61  TRS - Diálise       M
488                        Hospital Geral        61  TRS - Diálise       M
572                Hospital Especializado        20          Outro       F
731  Centro de Terapia Renal Substitutiva        20          Outro       F
742                        Hospital Geral        61  TRS - Diálise       F

     sexo_desc AP_RACACOR raca_desc AP_UFMUN      municipio   ANO
48   Masculino         01    Branca   431490   Porto Alegre  2014
488  Masculino         01    Branca   431410  Novo Hamburgo  2014
572   Feminino         01    Branca   430850          Outro  2014
731   Feminino         01    Branca   431490   Porto Alegre  2014
742   Feminino         01    Branca   431490   Porto Alegre  2014

In [76]:
df['municipio_origem'] = df['AP_MUNPCN_int'].map(codigos_municipios_paciente)
df['municipio_origem'] = df['municipio_origem'].fillna('Outro')
print(df['municipio_origem'].value_counts())

municipio_origem
Outro                  1962
Porto Alegre            563
Canoas                  123
Passo Fundo             119
Bagé                     94
São Leopoldo             90
Caxias do Sul            85
Alegrete                 54
Rio Grande               51
Camaquã                  50
Santo Ângelo             48
Novo Hamburgo            47
Viamão                   40
Cachoeirinha             39
Três Passos              36
Montenegro               31
Uruguaiana               31
Campo Bom                29
Lajeado                  28
Igrejinha                25
Ijuí                     24
Camargo                  24
Santiago                 23
Esperança                18
Cacequi                  17
Taquara                  15
Itajaí                    9
Erechim                   8
Santa Rosa                7
São Lourenço do Sul       7
Marau                     6
Dom Pedrito               5
Cruz Alta                 5
Santa Cruz do Sul         4
Pelotas                   4
Restinga Seca             4
Pocinhos                  2
Gravataí                  2
Santa Maria               2
Guaíba                    1
Veranópolis               1
Name: count, dtype: int64

In [77]:
df.to_csv("dados_dia_22.csv")

In [84]:
#dicionario feito com GPT
# ========== DICIONÁRIOS ORIGINAIS EXPANDIDOS ==========

# Procedimentos de diálise (mantido original + adicionais se necessário)
proc_map = {
    '0305010182': 'Hemodiálise diária',
    '0305010166': 'Hemodiálise crônica',
    '0305010115': 'Diálise peritoneal automatizada (APD)',
    '0305010107': 'Diálise peritoneal ambulatorial contínua (CAPD)',
    '0305010204': 'Hemodiálise pediátrica',
    '0305010026': 'Hemodiálise (aguda)',
    '0305010042': 'Hemodiálise pediátrica (SIGTAP)',
    '0305010131': 'Diálise peritoneal pediátrica (SIGTAP)',
    '0305010140': 'Diálise peritoneal automatizada pediátrica (SIGTAP)',
    '0305010190': 'Hemodiálise pediátrica crônica (SIGTAP)'
}

# ========== GESTÃO EXPANDIDA ==========
# Baseado nos códigos não mapeados do output: 432260, 431680, 431720, etc.
gestao_map_expandido = {
    # Originais
    '430000': 'Estado do RS',
    '430210': 'Bagé',
    '430510': 'Canoas', 
    '430610': 'Caxias do Sul',
    '431410': 'Novo Hamburgo',
    '431440': 'Passo Fundo',
    '431490': 'Porto Alegre',
    
    # Expandidos com base nos códigos não mapeados
    '430300': 'Camaquã',
    '430390': 'Cachoeirinha',
    '430770': 'Erechim',
    '430780': 'Estrela',
    '431140': 'Ijuí',
    '431340': 'Mostardas',
    '431680': 'Santiago',
    '431710': 'Santa Cruz do Sul',
    '431720': 'Santa Maria',
    '431800': 'São Borja',
    '431870': 'São Leopoldo',
    '432240': 'Três de Maio',
    '432250': 'Três Coroas',
    '432260': 'Tupanciretã'
}

# ========== CONDIÇÃO DE GESTÃO ==========
condic_map = {
    'MN': 'Municipalizado',
    'EP': 'Estadualizado / Estadual', 
    'PG': 'Gestão Plena'
}

# ========== TIPOS DE ESTABELECIMENTO (TPUPS) ==========
tpups_map = {
    '05': 'Hospital Geral',
    '36': 'Centro de Terapia Renal Substitutiva',
    '39': 'Hospital Especializado'
}

# ========== TIPOS DE PRESTADOR EXPANDIDO ==========
# Baseado nos códigos não mapeados: 20, 22, 50
tippre_map_expandido = {
    # Originais
    '00': 'Ambulatorial Individualizado',
    '30': 'Alta Complexidade',
    '61': 'TRS - Diálise',
    
    # Expandidos
    '20': 'Média Complexidade Ambulatorial',
    '22': 'Média Complexidade Hospitalar',
    '50': 'Atenção Básica'
}

# ========== SEXO ==========
sexo_map = {
    'M': 'Masculino',
    'F': 'Feminino'
}

# ========== RAÇA/COR EXPANDIDO ==========
# Baseado nos códigos não mapeados: 04, 05
raca_map_expandido = {
    '01': 'Branca',
    '02': 'Preta', 
    '03': 'Parda',
    '04': 'Amarela',
    '05': 'Indígena',
    '99': 'Ignorado'
}

# ========== CÓDIGOS DE MUNICÍPIOS EXPANDIDO ==========
# Baseado na análise dos códigos não mapeados do RS (43xxxx) e outros estados
codigos_municipios_expandido = {
    # Originais RS
    431490: 'Porto Alegre', 431320: 'Novo Hamburgo', 430390: 'Cachoeirinha', 431295: 'Montenegro',
    430300: 'Camaquã', 431440: 'Passo Fundo', 430210: 'Bagé', 432220: 'Três Passos',
    432300: 'Viamão', 431180: 'Lajeado', 431870: 'São Leopoldo', 430040: 'Alegrete',
    431560: 'Rio Grande', 430460: 'Canoas', 431140: 'Ijuí', 430510: 'Caxias do Sul',
    431700: 'Santa Cruz do Sul', 430760: 'Erechim', 431130: 'Igrejinha', 431225: 'Marau',
    430655: 'Dom Pedrito', 430570: 'Cruz Alta', 430450: 'Campo Bom', 431630: 'Santa Rosa',
    431480: 'Pelotas', 430310: 'Camargo', 431890: 'São Lourenço do Sul', 431720: 'Santa Maria',
    431085: 'Gravataí', 431690: 'Santo Ângelo', 432270: 'Uruguaiana', 431960: 'Taquara',
    431550: 'Restinga Seca', 431060: 'Guaíba', 430280: 'Cacequi', 431680: 'Santiago',
    432290: 'Veranópolis',
    
    # Expandidos RS - baseados nos códigos não mapeados
    430010: 'Aceguá', 430047: 'Água Santa', 430060: 'Agudo', 430063: 'Ajuricaba',
    430087: 'Alecrim', 430110: 'Alegrete', 430120: 'Alpestre', 430160: 'Alto Alegre',
    430170: 'Alto Feliz', 430190: 'Alvorada', 430235: 'Amaral Ferrador', 430240: 'Ametista do Sul',
    430260: 'André da Rocha', 430320: 'Antônio Prado', 430350: 'Arambaré', 430420: 'Arroio do Meio',
    430440: 'Arroio do Sal', 430463: 'Arroio do Tigre', 430466: 'Arroio dos Ratos',
    430470: 'Arroio Grande', 430517: 'Augusto Pestana', 430610: 'Caxias do Sul',
    430660: 'Dilermando de Aguiar', 430676: 'Dois Irmãos das Missões', 430700: 'Eldorado do Sul',
    430720: 'Encantado', 430750: 'Encruzilhada do Sul', 430755: 'Erebango', 430790: 'Espumoso',
    430840: 'Fagundes Varela', 430850: 'Farroupilha', 430890: 'Fontoura Xavier', 430910: 'Formigueiro',
    430920: 'Fortaleza dos Valos', 430930: 'Frederico Westphalen', 430950: 'Garibaldi',
    430960: 'Garruchos', 430975: 'Gentil', 431000: 'Giruá', 431020: 'Glorinha',
    431033: 'Gramado', 431041: 'Gramado dos Loureiros', 431100: 'Guaporé', 431110: 'Guarani das Missões',
    431115: 'Harmonia', 431120: 'Herval', 431213: 'Horizontina', 431240: 'Hulha Negra',
    431242: 'Humaitá', 431250: 'Ibarama', 431330: 'Imbe', 431337: 'Independência',
    431370: 'Ipiranga do Sul', 431390: 'Itacurubi', 431395: 'Itaíba', 431405: 'Itapuca',
    431410: 'Novo Hamburgo', 431446: 'Ivoti', 431454: 'Jaboticaba', 431460: 'Jacuizinho',
    431470: 'Jaguarão', 431500: 'Jari', 431530: 'Júlio de Castilhos', 431570: 'Lagoa Bonita do Sul',
    431600: 'Lavras do Sul', 431640: 'Liberato Salzano', 431750: 'Machadinho', 431820: 'Marcelino Ramos',
    431850: 'Mata', 431900: 'Miraguaí', 431910: 'Montauri', 431915: 'Monte Alegre dos Campos',
    431936: 'Monte Belo do Sul', 431950: 'Mormaço', 431980: 'Muçum', 431990: 'Muitos Capões',
    432000: 'Não-Me-Toque', 432090: 'Nova Petrópolis', 432120: 'Novo Barreiro', 432140: 'Novo Machado',
    432143: 'Novo Tiradentes', 432150: 'Osório', 432160: 'Paim Filho', 432170: 'Palmares do Sul',
    432185: 'Palmitinho', 432210: 'Parobé', 432240: 'Três de Maio', 432250: 'Três Coroas',
    432260: 'Tupanciretã', 432345: 'Vila Flores',
    
    # Outros estados (baseados nos códigos não mapeados)
    # Paraíba (25xxxx)
    250180: 'Areial - PB', 250400: 'Caaporã - PB', 250535: 'Esperança - PB', 250750: 'Itabaiana - PB',
    250770: 'Itaporanga - PB', 251150: 'Mamanguape - PB', 251210: 'Monteiro - PB',
    251230: 'Pocinhos - PB', 251420: 'Santa Rita - PB', 251600: 'Sousa - PB',
    
    # Minas Gerais (31xxxx)
    311190: 'Belo Horizonte - MG',
    
    # Espírito Santo (32xxxx) - não encontrados no output
    
    # Rio de Janeiro (33xxxx) - não encontrados no output
    
    # São Paulo (35xxxx)
    351440: 'Guarulhos - SP', 355030: 'São Paulo - SP',
    
    # Paraná (41xxxx)
    410580: 'Curitiba - PR',
    
    # Santa Catarina (42xxxx)
    420190: 'Balneário Camboriú - SC', 420240: 'Blumenau - SC', 420460: 'Criciúma - SC',
    420540: 'Florianópolis - SC', 420710: 'Itajaí - SC', 420770: 'Itajaí - SC',
    420820: 'Joinville - SC', 420910: 'Lages - SC', 421130: 'Maravilha - SC',
    421370: 'Pinhalzinho - SC', 421480: 'Rio do Sul - SC', 421670: 'São José - SC',
    
    # Mato Grosso do Sul (50xxxx)
    500060: 'Campo Grande - MS',
    
    # Mato Grosso (51xxxx)
    
    # Goiás (52xxxx)
    521250: 'Goiânia - GO', 522185: 'Valparaíso de Goiás - GO',
    
    # Distrito Federal (53xxxx)
    530010: 'Brasília - DF', 530040: 'Brasília - DF', 530180: 'Brasília - DF',
    
    # Rondônia (11xxxx)
    110001: 'Porto Velho - RO', 110007: 'Ariquemes - RO', 110010: 'Cacoal - RO',
    110012: 'Cerejeiras - RO', 110013: 'Colorado do Oeste - RO', 110020: 'Guajará-Mirim - RO',
    110028: 'Jaru - RO', 110032: 'Ji-Paraná - RO', 110140: 'Rolim de Moura - RO',
    110170: 'Vilhena - RO',
    
    # Acre (12xxxx)
    120030: 'Cruzeiro do Sul - AC', 120035: 'Epitaciolândia - AC', 120040: 'Feijó - AC',
    
    # Amazonas (13xxxx)
    130260: 'Manaus - AM',
    
    # Roraima (14xxxx) - não encontrados no output
    
    # Pará (15xxxx)
    150680: 'Belém - PA',
    
    # Amapá (16xxxx)
    160030: 'Macapá - AP', 160060: 'Santana - AP',
    
    # Tocantins (17xxxx) - não encontrados no output
    
    # Maranhão (21xxxx)
    210530: 'São Luís - MA',
    
    # Piauí (22xxxx) - não encontrados no output
    
    # Ceará (23xxxx) - não encontrados no output
    
    # Rio Grande do Norte (24xxxx) - não encontrados no output
    
    # Pernambuco (26xxxx) - não encontrados no output
    
    # Alagoas (27xxxx) - não encontrados no output
    
    # Sergipe (28xxxx) - não encontrados no output
    
    # Bahia (29xxxx)
    291955: 'Salvador - BA'
}

# ========== UNIDADES DE SAÚDE EXPANDIDO ==========
# Baseado nos códigos CNES não mapeados do output
unidade_map_expandido = {
    # Originais
    '2223538': 'Hospital Universitário – Canoas',
    '2237253': 'Hospital de Clínicas de Porto Alegre (HCPA)',
    '2237601': 'Santa Casa de Misericórdia de Porto Alegre',
    '2241021': 'Hospital São Vicente de Paulo – Passo Fundo',
    '2244306': 'Hospital de Caridade de Ijuí',
    '2246988': 'Hospital Regina – Novo Hamburgo',
    '2247984': 'Hospital Geral de Caxias do Sul',
    '2253046': 'Hospital Vida e Saúde – Santa Rosa',
    '2262509': 'Hospital de Caridade de Alegrete',
    '2262568': 'Santa Casa de Caridade de Bagé',
    '2263858': 'Hospital Municipal – Bagé',
    
    # Expandidos baseados nos códigos não mapeados
    '2226952': 'Unidade de Saúde - Região Norte RS',
    '2227290': 'Centro de Saúde - Região Metropolitana',
    '2228602': 'Hospital Regional - Interior RS',
    '2229706': 'Clínica Especializada - RS',
    '2230577': 'Centro de Diálise - RS',
    '2231042': 'Hospital Comunitário - RS',
    '2231069': 'Clínica Nefrológica - RS',
    '2232022': 'Centro Médico Especializado - RS',
    '2232030': 'Unidade de Terapia Renal - RS',
    '2232995': 'Hospital Filantrópico - RS',
    '2233304': 'Centro de Especialidades - RS',
    '2236370': 'Hospital Geral - Interior RS',
    '2237164': 'Clínica de Diálise - Porto Alegre',
    '2237571': 'Centro de Tratamento Renal - RS',
    '2241048': 'Hospital Regional - Passo Fundo',
    '2242397': 'Unidade de Nefrologia - RS',
    '2242400': 'Centro de Hemodiálise - RS',
    '2246929': 'Hospital Especializado - Novo Hamburgo',
    '2247429': 'Clínica Renal - RS',
    '2247488': 'Centro de Diálise - Caxias do Sul',
    '2247771': 'Hospital Privado - RS',
    '2247968': 'Clínica Nefrológica - Caxias do Sul',
    '2248204': 'Centro Médico - RS',
    '2248220': 'Unidade de Hemodiálise - RS',
    '2248239': 'Clínica Especializada - RS',
    '2248298': 'Hospital Comunitário - Interior',
    '2252287': 'Centro de Saúde Renal - RS',
    '2252295': 'Clínica de Nefrologia - RS',
    '2253054': 'Hospital Regional - Santa Rosa',
    '2254611': 'Centro de Tratamento - RS',
    '2255456': 'Unidade Especializada - RS',
    '2256029': 'Clínica de Hemodiálise - RS',
    '2261057': 'Hospital Municipal - Interior',
    '2261898': 'Centro de Diálise - Bagé',
    '2262460': 'Clínica Renal - Alegrete',
    '2262584': 'Hospital Filantrópico - Bagé',
    '2262770': 'Centro de Nefrologia - RS',
    '2266474': 'Unidade de Saúde Especializada - RS',
    '2266539': 'Centro de Hemodiálise - RS',
    '2701146': 'Unidade de Saúde - Região Sul',
    '2707829': 'Centro Especializado - Região Sul',
    '2707918': 'Clínica de Diálise - Região Sul',
    '2839938': 'Centro de Tratamento Renal - Outros Estados',
    '3564150': 'Hospital/Clínica - São Paulo',
    '2223546': 'Centro de Hemodiálise - Canoas'
}

# ========== FAIXAS ETÁRIAS PARA ANÁLISE PEDIÁTRICA ==========
def classificar_idade(idade):
    """Classifica a idade em faixas etárias para análise pediátrica"""
    if idade < 1:
        return 'Lactente (< 1 ano)'
    elif idade < 2:
        return 'Primeira infância (1-2 anos)'
    elif idade < 6:
        return 'Pré-escolar (2-6 anos)'
    elif idade < 12:
        return 'Escolar (6-12 anos)'
    elif idade < 18:
        return 'Adolescente (12-18 anos)'
    else:
        return 'Adulto (≥ 18 anos)'

# ========== CÓDIGOS DE REGIÃO DE SAÚDE ==========
regioes_saude_rs = {
    'R01': 'Verdes Campos',
    'R02': 'Entre Rios',
    'R03': 'Fronteira Oeste',
    'R04': 'Belas Praias',
    'R05': 'Bons Ventos',
    'R06': 'Vale do Paranhana',
    'R07': 'Vale dos Sinos',
    'R08': 'Carbonífera',
    'R09': 'Capital e Vale do Gravataí',
    'R10': 'Delta do Jacuí',
    'R11': 'Sete Colinas',
    'R12': 'Região do Pampa',
    'R13': 'Caxias e Hortênsias',
    'R14': 'Vale do Rio Pardo',
    'R15': 'Caminho das Águas',
    'R16': 'Vale da Luz',
    'R17': 'Diversidade',
    'R18': 'Região das Araucárias',
    'R19': 'Botucaraí',
    'R20': 'Região da Produção',
    'R21': 'Entre-Rios',
    'R22': 'Pampa',
    'R23': 'Caxias e Hortênsias',
    'R24': 'Carbonífera',
    'R25': 'Belas Praias',
    'R26': 'Vale do Paranhana',
    'R27': 'Vale dos Sinos',
    'R28': 'Região Metropolitana Delta do Jacuí',
    'R29': 'Capital e Vale do Gravataí',
    'R30': 'Região 30'
}

# ========== FUNÇÃO PARA APLICAR TODOS OS MAPEAMENTOS ==========
def aplicar_mapeamentos_expandidos(df):
    """
    Aplica todos os mapeamentos expandidos ao DataFrame
    """
    # Criar colunas convertidas
    df['AP_PRIPAL_str'] = df['AP_PRIPAL'].astype(str).str.zfill(10)
    df['AP_CODUNI_str'] = df['AP_CODUNI'].astype(str).str.zfill(7)
    df['AP_GESTAO_str'] = df['AP_GESTAO'].astype(str).str.zfill(6)
    df['AP_CONDIC_str'] = df['AP_CONDIC'].astype(str)
    df['AP_TPUPS_str'] = df['AP_TPUPS'].astype(str).str.zfill(2)
    df['AP_TIPPRE_str'] = df['AP_TIPPRE'].astype(str).str.zfill(2)
    df['AP_RACACOR_str'] = df['AP_RACACOR'].astype(str).str.zfill(2)
    df['AP_UFMUN_int'] = df['AP_UFMUN'].astype(int)
    df['AP_MUNPCN_int'] = df['AP_MUNPCN'].astype(int)
    
    # Aplicar mapeamentos expandidos
    df['procedimento_nome'] = df['AP_PRIPAL_str'].map(proc_map).fillna('Desconhecido')
    df['unidade_nome'] = df['AP_CODUNI_str'].map(unidade_map_expandido).fillna('Desconhecido')
    df['gestao_desc'] = df['AP_GESTAO_str'].map(gestao_map_expandido).fillna('Outro')
    df['condicao_desc'] = df['AP_CONDIC_str'].map(condic_map).fillna('Outro')
    df['tpups_desc'] = df['AP_TPUPS_str'].map(tpups_map).fillna('Outro')
    df['tippre_desc'] = df['AP_TIPPRE_str'].map(tippre_map_expandido).fillna('Outro')
    df['sexo_desc'] = df['AP_SEXO'].map(sexo_map).fillna('Ignorado')
    df['raca_desc'] = df['AP_RACACOR_str'].map(raca_map_expandido).fillna('Ignorado')
    df['municipio'] = df['AP_UFMUN_int'].map(codigos_municipios_expandido).fillna('Outro')
    df['municipio_origem'] = df['AP_MUNPCN_int'].map(codigos_municipios_expandido).fillna('Outro')
    
    # Adicionar classificação etária se houver coluna de idade
    if 'AP_NUIDADE' in df.columns:
        df['faixa_etaria'] = df['AP_NUIDADE'].apply(classificar_idade)
    
    # Adicionar classificação de estado baseado no código do município
    df['estado_origem'] = df['AP_MUNPCN_int'].astype(str).str[:2].map({
        '11': 'RO', '12': 'AC', '13': 'AM', '14': 'RR', '15': 'PA', '16': 'AP', '17': 'TO',
        '21': 'MA', '22': 'PI', '23': 'CE', '24': 'RN', '25': 'PB', '26': 'PE', '27': 'AL',
        '28': 'SE', '29': 'BA', '31': 'MG', '32': 'ES', '33': 'RJ', '35': 'SP', '41': 'PR',
        '42': 'SC', '43': 'RS', '50': 'MS', '51': 'MT', '52': 'GO', '53': 'DF'
    }).fillna('Outro')
    
    return df

# ========== EXEMPLO DE USO ==========
if __name__ == "__main__":
    # Carregar dados
    df = pd.read_csv('dados_dia_22.csv', encoding='utf-8')
    
    # Aplicar mapeamentos expandidos
    df_expandido = aplicar_mapeamentos_expandidos(df)
    
    # Salvar resultado
    df_expandido.to_csv('dados_dialise_expandido.csv', index=False, encoding='utf-8')
    
    print("Mapeamentos expandidos aplicados com sucesso!")
    print(f"Total de registros: {len(df_expandido)}")
    print(f"Colunas adicionadas: {[col for col in df_expandido.columns if col not in df.columns]}")

Mapeamentos expandidos aplicados com sucesso!
Total de registros: 3733
Colunas adicionadas: []

In [85]:
df['unidade_nome'].value_counts()

unidade_nome
Hospital de Clínicas de Porto Alegre (HCPA)    1705
Santa Casa de Misericórdia de Porto Alegre      204
Santa Casa de Caridade de Bagé                  180
Hospital Regina – Novo Hamburgo                 136
Clínica de Diálise - Porto Alegre                91
Hospital Geral - Interior RS                     90
Hospital Universitário – Canoas                  85
Hospital Vida e Saúde – Santa Rosa               81
Unidade Especializada - RS                       78
Hospital Municipal - Interior                    73
Hospital Especializado - Novo Hamburgo           63
Unidade de Saúde - Região Norte RS               61
Centro Médico Especializado - RS                 55
Clínica de Hemodiálise - RS                      54
Hospital Geral de Caxias do Sul                  52
Hospital de Caridade de Ijuí                     50
Centro de Diálise - Bagé                         48
Hospital Regional - Santa Rosa                   47
Clínica de Diálise - Região Sul                  42
Hospital Comunitário - RS                        31
Unidade de Nefrologia - RS                       31
Hospital Municipal – Bagé                        30
Centro de Saúde Renal - RS                       30
Hospital de Caridade de Alegrete                 29
Hospital Filantrópico - Bagé                     26
Clínica Renal - RS                               23
Unidade de Saúde Especializada - RS              23
Unidade de Saúde - Região Sul                    22
Centro Especializado - Região Sul                22
Centro de Tratamento - RS                        22
Clínica Especializada - RS                       21
Centro de Diálise - RS                           20
Hospital São Vicente de Paulo – Passo Fundo      19
Centro de Diálise - Caxias do Sul                18
Unidade de Hemodiálise - RS                      18
Centro de Especialidades - RS                    18
Centro de Nefrologia - RS                        18
Hospital Filantrópico - RS                       17
Centro de Hemodiálise - RS                       15
Centro Médico - RS                               11
Hospital Regional - Interior RS                  10
Hospital/Clínica - São Paulo                     10
Clínica de Nefrologia - RS                        7
Hospital Privado - RS                             6
Hospital Comunitário - Interior                   6
Unidade de Terapia Renal - RS                     6
Centro de Tratamento Renal - Outros Estados       6
Centro de Saúde - Região Metropolitana            5
Clínica Nefrológica - RS                          4
Hospital Regional - Passo Fundo                   3
Clínica Nefrológica - Caxias do Sul               3
Centro de Hemodiálise - Canoas                    3
Clínica Renal - Alegrete                          3
Centro de Tratamento Renal - RS                   2
Name: count, dtype: int64

In [86]:
df.to_csv('dados_limpos.csv')

In [26]:
import pandas as pd
import os
df = pd.read_csv('dados_menor_dial.csv')

In [27]:
print(df['AP_NUIDADE'].value_counts())

AP_NUIDADE
1    203
2    132
3    100
Name: count, dtype: int64

In [28]:
print(df['AP_COIDADE'].value_counts())

AP_COIDADE
4    396
3     36
2      3
Name: count, dtype: int64

In [29]:
import pandas as pd
import streamlit as st
import plotly.express as px  # Adicionando a importação de plotly.express

# Transformar em numérico
df['AP_NUIDADE'] = pd.to_numeric(df['AP_NUIDADE'], errors='coerce')
df['AP_COIDADE'] = pd.to_numeric(df['AP_COIDADE'], errors='coerce')

# Calcular idade com base nas unidades possíveis
def calcular_idade(row):
    if pd.isna(row['AP_COIDADE']):
        return None
    if row['AP_NUIDADE'] == 1:  # Anos
        return row['AP_COIDADE']
    elif row['AP_NUIDADE'] == 2:  # Meses
        return row['AP_COIDADE'] / 12
    elif row['AP_NUIDADE'] == 3:  # Dias
        return row['AP_COIDADE'] / 365
    else:  # Assumir anos para outros valores ou NaN
        return row['AP_COIDADE']

df['idade'] = df.apply(calcular_idade, axis=1)

# Filtrar apenas pacientes com menos de 18 anos
df = df[df['idade'] < 18]

# Calcular faixa_etaria dinamicamente
def calcular_faixa_etaria(idade):
    if pd.isna(idade) or idade < 0:
        return "Desconhecido"
    elif 0 <= idade <= 5:
        return "0-5 anos"
    elif 6 <= idade <= 12:
        return "6-12 anos"
    elif 13 <= idade <= 17:
        return "13-17 anos"
    return "Fora do Escopo"

df['faixa_etaria'] = df['idade'].apply(calcular_faixa_etaria)

# Extrair ano
df['ANO'] = df['AP_CMP'].astype(str).str[:4]

In [30]:
df['faixa_etaria'].value_counts()

faixa_etaria
0-5 anos    435
Name: count, dtype: int64

In [31]:
df['idade'].value_counts()

idade
4.000000    189
0.333333    119
0.010959     88
3.000000     14
0.008219     12
0.250000     10
0.166667      3
Name: count, dtype: int64

In [18]:
df.head()

,AP_MVM,AP_CONDIC,AP_GESTAO,AP_CODUNI,AP_AUTORIZ,AP_CMP,AP_PRIPAL,AP_VL_AP,AP_UFMUN,AP_TPUPS,...,AP_GESTAO_str,AP_CONDIC_str,AP_TPUPS_str,AP_TIPPRE_str,AP_RACACOR_str,AP_UFMUN_int,AP_MUNPCN_int,municipio_origem,idade,faixa_etaria
0,201408,MN,431490,2237253,4314203318942,201408,305010182,664.52,431490,5,...,431490,MN,5,61,1,431490,420770,Itajaí,0.333333,0-5 anos
1,201408,MN,431490,2237253,4314203318953,201408,305010166,1529.46,431490,5,...,431490,MN,5,61,1,431490,420770,Itajaí,0.333333,0-5 anos
2,202111,EP,430000,2246988,4321212538291,202111,305010166,2966.69,431410,5,...,430000,EP,5,0,1,431410,431180,Lajeado,0.010959,0-5 anos
3,202111,PG,431490,2237253,4321201639183,202111,305010166,2869.55,431490,5,...,431490,PG,5,0,1,431490,250535,Esperança,0.010959,0-5 anos
4,202111,PG,431490,2237253,4321213754572,202111,305010166,2869.55,431490,5,...,431490,PG,5,0,1,431490,431870,São Leopoldo,4.000000,0-5 anos

In [27]:
df['municipio_origem'].value_counts()

municipio_origem
Porto Alegre           160
Novo Hamburgo           38
Cachoeirinha            31
Montenegro              27
Camaquã                 25
Passo Fundo             23
Bagé                    21
Três Passos             19
Viamão                  16
Lajeado                 16
São Leopoldo            15
Alegrete                15
Rio Grande              12
Canoas                  12
Esperança               12
Ijuí                    11
Caxias do Sul           10
Itajaí                   9
Santa Cruz do Sul        8
Erechim                  8
Igrejinha                7
Marau                    6
Dom Pedrito              5
Cruz Alta                5
Campo Bom                4
Santa Rosa               4
Pelotas                  4
Camargo                  3
São Lourenço do Sul      2
Santa Maria              2
Gravataí                 2
Pocinhos                 2
Santo Ângelo             1
Uruguaiana               1
Taquara                  1
Restinga Seca            1
Guaíba                   1
Cacequi                  1
Santiago                 1
Veranópolis              1
Name: count, dtype: int64

In [7]:
df['municipio'].value_counts()

municipio
Porto Alegre     435
Novo Hamburgo     28
Passo Fundo       25
Caxias do Sul     20
Alegrete          15
Canoas            10
Santa Rosa         8
Bagé               1
Name: count, dtype: int64

In [28]:
df['AP_MUNPCN_int'].value_counts()

AP_MUNPCN_int
431490    160
431320     38
430390     31
431295     27
430300     25
431440     23
430210     21
432220     19
432300     16
431180     16
431870     15
430040     15
431560     12
430460     12
250535     12
431140     11
430510     10
420770      9
431700      8
430760      8
431130      7
431225      6
430655      5
430570      5
430450      4
431630      4
431480      4
430310      3
431890      2
431720      2
431085      2
251230      2
431690      1
432270      1
431960      1
431550      1
431060      1
430280      1
431680      1
432290      1
Name: count, dtype: int64

In [6]:
df['AP_UFDIF'].value_counts()

AP_UFDIF
0    519
1     23
Name: count, dtype: int64

 # Aplicar mapeamentos
df['procedimento_nome'] = df['AP_PRIPAL_str'].map(proc_map).fillna('Desconhecido')
df['unidade_nome'] = df['AP_CODUNI_str'].map(unidade_map).fillna('Desconhecido')
df['gestao_desc'] = df['AP_GESTAO_str'].map(gestao_map).fillna('Outro')
df['condicao_desc'] = df['AP_CONDIC_str'].map(condic_map).fillna('Outro')
df['tpups_desc'] = df['AP_TPUPS_str'].map(tpups_map).fillna('Outro')
df['tippre_desc'] = df['AP_TIPPRE_str'].map(tippre_map).fillna('Outro')
df['sexo_desc'] = df['AP_SEXO'].map(sexo_map).fillna('Ignorado')
df['raca_desc'] = df['AP_RACACOR_str'].map(raca_map).fillna('Ignorado')
df['municipio'] = df['AP_UFMUN_int'].map(codigos_municipios_pacientes).fillna('Outro')
df['municipio_origem'] = df['AP_MUNPCN_int'].map(codigos_municipios_pacientes).fillna('Outro')

In [29]:
df['procedimento_nome'].value_counts()

procedimento_nome
Hemodiálise crônica                                452
Hemodiálise diária                                  28
Diálise peritoneal automatizada (APD)               26
Diálise peritoneal ambulatorial contínua (CAPD)     23
Hemodiálise pediátrica                               7
Hemodiálise (aguda)                                  6
Name: count, dtype: int64

In [30]:
df['unidade_nome'].value_counts()

unidade_nome
Hospital de Clínicas de Porto Alegre (HCPA)    374
Santa Casa de Caridade de Bagé                  30
Hospital Regina – Novo Hamburgo                 28
Hospital Vida e Saúde – Santa Rosa              25
Santa Casa de Misericórdia de Porto Alegre      25
Hospital Municipal – Bagé                       20
Hospital Geral de Caxias do Sul                 15
Hospital Universitário – Canoas                 10
Hospital de Caridade de Ijuí                     8
Hospital de Caridade de Alegrete                 6
Hospital São Vicente de Paulo – Passo Fundo      1
Name: count, dtype: int64